### ISSUE TITLE
Interface to create new Issue

### ISSUE THREAD

**Issue by GlancingMind** [GlancingMind/git-bug#1]
The WebUI must have an Interface to create new Issues.
An Issue has a title and a description. Refer to the TermUI for inspiration.

**Comment by claudioantonio** [comment]
Take a look at https://github.com/MichaelMure/git-bug/issues/158.

**Comment by LenaNoctua** [comment]
@claudioantonio What exactly did you mean by the Todo "rowsMin support"?

**Comment by claudioantonio** [comment]
Hi @LenaNoctua ! I suppose You are referring to line 94 at CommentInput.tsx.
rows="4" // TODO: rowsMin support

The property rows from TextField define a fixed number of line for the TextArea. Maybe the commit author had intention to allow it have a smaller number of lines on window resizing... 🤔
