### ISSUE TITLE
Improve Navigation

### ISSUE THREAD

**Issue by GlancingMind** [GlancingMind/git-bug#10]
Currently the Navigation is not very clear. The user should have a visual cue,
which part of the UI is currently seen. E.g. If a user clicks on an Issue, it's details 
will be revealed but how to get back to the issue list.
This may be improved by implementing a navigation menu with all importent links.
E.g. Issue List, Search, Labels, Milestones etc.

**Comment by LenaNoctua** [comment]
![grafik](https://user-images.githubusercontent.com/77456362/109406769-175fec00-797c-11eb-83f4-e346cd55dd88.png)
![grafik](https://user-images.githubusercontent.com/77456362/109406792-38284180-797c-11eb-9f51-c36c77b5dcd5.png)
I added a simple backlink to the detail view and also a simple 404 page with backlink.

**Comment by LenaNoctua** [comment]
![grafik](https://user-images.githubusercontent.com/77456362/109702294-52d50300-7b94-11eb-9424-8a34643990c3.png)

Backbutton is now sticky.

**Comment by LenaNoctua** [comment]
After creation of a bug the user is now redirected to the bugs detail page as discussed with @GlancingMind.
