### ISSUE TITLE
Allow users to inspect their current identity details

### ISSUE THREAD

**Issue by GlancingMind** [GlancingMind/git-bug#12]
It would be of interest to see the details of the currently used identity in
the WebUI. At the moment, only the username is displayed with the avatar.
It would be good to also see the used email and the user id.

**Comment by GlancingMind** [comment]
Maybe add [h-cards annotations](https://indieweb.org/h-card) to the fields.

**Comment by LenaNoctua** [comment]
Is it about id or humanId? What about the difference between displayName and name? I am confused.

**Comment by GlancingMind** [comment]
If you are talking about:
> Maybe add [h-cards annotations](https://indieweb.org/h-card) to the fields.
Ignore may ignore it. It was more of a note to myself.

**Comment by MichaelMure** [comment]
If this can be thought as the beginning of a page like https://github.com/settings/profile that'd be great.

**Comment by LenaNoctua** [comment]
![Bildschirmfoto von 2021-03-08 17-35-35](https://user-images.githubusercontent.com/77456362/110351186-dbd8b800-8034-11eb-9c2c-34c23fa7f7cc.png)
Looks like that now, but I am not sure what about this isProtected-field.

**Comment by MichaelMure** [comment]
This field indicate if the identity is protected, that is if you require the private key to use it. You could indicate that with a 🔐 somewhere. What about hiding the fields not set?

**Comment by LenaNoctua** [comment]
How is this value set? I cannot find it in the Readme so that I can test it.

**Comment by MichaelMure** [comment]
The code to set it doesn't exist yet. It will be done by adding/generating a private key for your identity.

**Comment by LenaNoctua** [comment]
Ok don't know how to do it with the docker file. @GlancingMind Can you please help?

**Comment by GlancingMind** [comment]
> If this can be thought as the beginning of a page like https://github.com/settings/profile that'd be great.

Is it already supported to change the name or email of an identity?
Or is it required to generate another identity and then adopt it?

**Comment by LenaNoctua** [comment]
Hmm, okay, I cannot find a way to test this value atm :-/

**Comment by MichaelMure** [comment]
> Is it already supported to change the name or email of an identity?
> Or is it required to generate another identity and then adopt it?

It's supported in the core but the CLI tooling is missing.

**Comment by GlancingMind** [comment]
So it's also not possible to edit the name and email of an identity via graphql?

**Comment by MichaelMure** [comment]
Not yet. Someone has to write the graphQL mutation for that.

**Comment by GlancingMind** [comment]
The issues I worked on didn't require me to dig much into GraphQL.
Do you mean something like [this](https://github.com/GlancingMind/git-bug/blob/upstream-dark-colorscheme/webui/src/components/BugTitleForm/SetTitle.graphql)

**Comment by MichaelMure** [comment]
That's the first step, to define the schema.
Second step is to re-generate the server code: https://github.com/MichaelMure/git-bug/blob/master/api/graphql/handler.go#L1
Last step is to actually implement the mutation (that is, follow where that doesn't compile and fill the gaps).

**Comment by GlancingMind** [comment]
As go is a bit out of scope for our course, I would rather like to extract a editable profile page to another issue.

**Comment by LenaNoctua** [comment]
I did a rebase to maybe have it easier to refactor this as an extra page and merge it later.

**Comment by LenaNoctua** [comment]
And to use the dark mode  :)

**Comment by LenaNoctua** [comment]
![grafik](https://user-images.githubusercontent.com/77456362/111090097-c2e96e80-852e-11eb-8c4d-fe8714885e84.png)

Made it a page now.

**Comment by LenaNoctua** [comment]
![grafik](https://user-images.githubusercontent.com/77456362/111708288-e0c41580-8845-11eb-8e39-6e5a5dcf492e.png)
Added bug list

**Comment by GlancingMind** [comment]
Note to myself. Link from user names to profile page.

**Comment by GlancingMind** [comment]
Did some layout changes to prevent long names from destroying the layout. How does it look like? 
![image](https://user-images.githubusercontent.com/9444609/111881800-85fbfc80-89b2-11eb-9010-e6f2fbfaebaf.png)
![image](https://user-images.githubusercontent.com/9444609/111881812-901dfb00-89b2-11eb-9830-c9159c93a6bd.png)

**Comment by MichaelMure** [comment]
What about having a full blown timeline instead of just listing the bugs?

**Comment by GlancingMind** [comment]
> What about having a full blown timeline instead of just listing the bugs?

Nothing against it. Would like to see something like GitHub has, but some of our team would like to present our changes this coming week. I'm not sure if we could pull this off in that short time.
