### ISSUE TITLE
Interface to edit Issues

### ISSUE THREAD

**Issue by GlancingMind** [GlancingMind/git-bug#4]
The WebUI must allow a user to edit an Issue.
Access right are currently ignored like in the TermUI.

Edit: Editing the issue title is already implemeneted. Lets also allow to edit comments.
E.g. add a pencil icon to comment-header. If a user clicks on this icon, the message should be editable.

**Comment by claudioantonio** [comment]
Take a look at https://github.com/MichaelMure/git-bug/issues/535

**Comment by MichaelMure** [comment]
I suppose that's about editing comments?

**Comment by GlancingMind** [comment]
> I suppose that's about editing comments?

Depends if the backend already supports "versioning" of the comments.
E.g. like in Stackoverflow or GitHub, when a user edits an answer/comment.
Otherwise I would see this as closed, as the title of the issue is already editable.

**Comment by MichaelMure** [comment]
Editing comments (and the initial bug description) is supported everywhere but the webUI IIRC.

**Comment by GlancingMind** [comment]
Oh, then I think this issue has still potential. Will update the description.

**Comment by GlancingMind** [comment]
Will take over work on this one.

**Comment by GlancingMind** [comment]
Note to myself: If window is closed, restore entered content on next "visit".
