### ISSUE TITLE
Improve the search field with a query builder.

### ISSUE THREAD

**Issue by GlancingMind** [GlancingMind/git-bug#5]
The Issue search currently does not support searching for arbitrary strings.
It's better to replace the text input field with some custom query builder.

Currently following filter are allowed:
- status:open, status:closed
- author:<query>
- title:<title>
- label:<label>
- no:label

NOTE: Better to fix the search to allow arbitrary strings, but this will likely
require Go knowledge and is better handled in another Issue.

**Comment by GlancingMind** [comment]
Free text search seem to work for the current master branch.
So replacing the search field is no longer required.
Instead just implementing a query builder for the UX.

**Comment by MichaelMure** [comment]
To implement this, you will likely have to need some robust control over the query, which likely means you will have to re-implement the lexer/parser (https://github.com/MichaelMure/git-bug/tree/master/query) in javascript. Once you have that you will be able to change the value, add qualifiers ... without too much hassle.

**Comment by GlancingMind** [comment]
I thought more about a separate page with a form and some inputs for author, title, etc.
The form could then concatenate all given input values with the respective key.
E.g. Values in an author field would be prefixed with "author:" and then they all will be concatenated to one search string.
This could be implemented trivially, as the current search field already supports some search parameters, but lacks the discoverability of them. (How can a user know, that prefixing a string with "author:" will perform a search by author.)

Maybe I didn't understand correctly.

**Comment by MichaelMure** [comment]
That would work indeed but IMHO the best UX I can think of is github's one. As you can see on https://github.com/GlancingMind/git-bug/issues, you can:
1. visualize your query in text form (very compact and readable)
2. edit your query manually if you know how to (very efficient)
3. edit your query through a bunch of drop-down and clics

I'm just hoping that you would go in that direction ;-)

It's not necessarily harder as soon as you have the lexer/parser in javascript (~300 lines).

**Comment by MichaelMure** [comment]
The beauty of what github has done with that UX is that it also *teach* the user the textual query language, which can then be used in the CLI and termUI.

**Comment by MichaelMure** [comment]
Again, you do what you want with your school project :-)

**Comment by GlancingMind** [comment]
I value your feedback. Let's see what we get done. :-)
