### ISSUE TITLE
Interface to label Issues

### ISSUE THREAD

**Issue by GlancingMind** [GlancingMind/git-bug#6]
Currently the WebUI only supports to display Labels on already labeled Issues.
Implement an Interface to the Issue view which allows to add already existing labels to the Issue.
May be a search box which searches for all defined labels. Possible solve with #1 .

**Comment by timbkr** [comment]
first steps already  taken in #8, will likely be resolved together

**Comment by MichaelMure** [comment]
FYI, the graphQL API expose `validLabels` in `Repository` to know what label can be used. At the moment it's the set of labels existing on other issues but that could change in the future if some form of project settings exist where the valid labels are defined.
